server:
  port: 8888
encrypt:
  key: valiko
  api: https://github.com/garikhgh/spring-cloud


spring:
  security:
    user:
      name: admin
      password: admin
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/garikhgh/spring-cloud
          default-label: main
          search-paths:
          - station*
#          repos:
#            perf:
#              pattern: '*/perf'